### PR TITLE
Update API role for removal of contentqa engine

### PR DESCRIPTION
**Pull request by markbreedlove**
See https://github.com/dpla/platform/pull/40 and https://issues.dp.la/issues/8262

The `contentqa` engine is being removed from the platform (api) app, so we must remove the deployment rake tasks and service handlers pertaining to it.

### CODE REVIEW

**Comment by anarchivist** [comment]
Should we clean up `roles/api/tasks/main.yml` to remove [lines 49-80](https://github.com/dpla/automation/blob/develop/ansible/roles/api/tasks/main.yml#L49-L80) and [lines 104-114](https://github.com/dpla/automation/blob/develop/ansible/roles/api/tasks/main.yml#L104-L114), and to add steps that remove the control and init scripts? 

Similarly, should we delete `delayed_job_api.sh.j2`, `etc_init.d_delayed_job_api.j2`,  and `qa_htpasswd.j2` from `roles/api/templates`?

**Comment by markbreedlove** [comment]
Oh, yikes, yes.

**Comment by markbreedlove** [comment]
Plus the Nginx block for `/qa` ...

**Comment by markbreedlove** [comment]
Hang on, one more thing to add ...

**Comment by markbreedlove** [comment]
@anarchivist: I think I'm done making my changes.

**Comment by anarchivist** [comment]
OK, looks good to me. Adding a reference to the issue I created yesterday. https://issues.dp.la/issues/8262

**Pull request merged**
