### PR TITLE
Heidrun: add base URI for providers to settings

### PR DESCRIPTION
**Pull request by anarchivist**

### CODE REVIEW

**Comment by markbreedlove** [comment]
Looks pretty simple.  Can you verify whether it's safe for this to be hardcoded?  There is a `frontend_hostname` variable that we may be able to use here.

**Comment by anarchivist** [comment]
@markbreedlove The URIs for the providers are not yet dereferenceable, and should be the same across both dev, staging, and production. I think it should be safe for this value to be hardcoded.

**Comment by markbreedlove** [comment]
@anarchivist: OK!  In that case, I will merge this.

**Comment by anarchivist** [comment]
:clap:

**Pull request merged**
