### PR TITLE
Add the svc-backup user to the postfix generic profile

### PR DESCRIPTION
**Pull request by moltude**

### CODE REVIEW

**Comment by anarchivist** [comment]
Looks good. I'm imagining that the user will get added as part of an other pull request?

**Comment by moltude** [comment]
yeah, I looked through the automation repo and wasn't sure how to do that.

**Comment by markbreedlove** [comment]
Here's an example:
https://github.com/dpla/automation/blob/v2.5.1/ansible/roles/common_web/tasks/main.yml#L44-L50

You'll want to create a new Ansible role for the purpose of creating the user, installing the backup script, and putting it on a crontab. The `tasks/main.yml` playbook for that role would be the place to put the account-creation task.

**Comment by markbreedlove** [comment]
We're using AWS Lambda for EBS snapshots now, so I'm closing this out.

**Pull request closed without merging**
