### PR TITLE
Add development support for SSL

### PR DESCRIPTION
**Pull request by markbreedlove**
* Revise the dev_loadbalancer role so that HAProxy does SSL
* Update the `omeka` and `site_proxy` roles to allow the API to use SSL.

This PR is bound to the `frontend` changes currently under review as https://github.com/dpla/frontend/pull/83

### CODE REVIEW

**Comment by markbreedlove** [comment]
Hold on before reviewing; need to change one thing.

**Comment by markbreedlove** [comment]
OK, ready for review.

**Comment by markbreedlove** [comment]
Here's some information I'm going to add to the next `automation` version's release notes, which should help with testing.

* You need to have `api_default_protocol` to your `group_vars/all` file
* If you're switching to https by modifying api_default_protocol, you need to re-run the frontend, exhibitions, and site_proxy playbooks.
* You need to have the latest version of `frontend`.
* Read this re configuring your browser to use the `local.dp.la` self-signed certificate:
http://blog.getpostman.com/2014/01/28/using-self-signed-certificates-with-postman/  I have found that you get by without restarting Chrome, if you use it. If you recreate the `loadbal` VM or you regenerate the SSL certificate, you'll have to redo the steps in that blog post to replace the trusted local.dp.la certificate in your chain.

Upgrade instructions:
```
ssh <you>@loadbal
sudo aptitude purge hatop
sudo aptitude purge haproxy
exit
$ ansible-playbook -u <you> -i development playbooks/dev_loadbalancer.yml
```

**Comment by markbreedlove** [comment]
I'm working on adding some of that the the README, to go along with this pull request...

**Comment by moltude** [comment]
👍

**Comment by markbreedlove** [comment]
This should be ready for review again.

Please **do not merge yet**. I'll want to squash the last commit before it's merged.

**Comment by moltude** [comment]
Will do

**Comment by markbreedlove** [comment]
An update on this PR's scope. The changes are now:

* Add development support for SSL
* Add port to es_cluster_loadbal
* Fix Exhibitions frontend URL variable
* Clean up redundancy in dev_ingestion_all.yml

I am debating how to squash these. All but the last are in some way related to enabling SSL in development. I think the last one should remain a separate commit.

**Comment by moltude** [comment]
@markbreedlove I think it makes sense to squash those four SSL commits together 
979bc18
3bd830f
419b130
2b28564

**Comment by moltude** [comment]
@markbreedlove squashed and good to merge into develop.

**Comment by markbreedlove** [comment]
@moltude Yes, I think it's good to merge.

**Pull request merged**
